minecraft-version: 1.6.4
# Please ensure that the names used on this list are the same
# as the mod's name in this link:
# http://bot.notenoughmods.com/1.6.4.json
mods:
    # - name: ICBM ## It is ICBMContraption, ICBMExplosion, etc.
    # - name: TheBarrelsMod ## Don't need it as we have Factorization.
    #- name: BetterStorage ## Removed as buggy and too exploitable.
    #- name: SoulShards ## Disabled because it reduces the value of vanilla spawners
    #- name: Traincraft ## removed due to being buggy.
    #- name: Treefeller ## If I am going to use a tree cutter mod it'll be treecap nerfed.
    #- name: WholeTreeAxe ## better mods for this.
    #- name: WorldStateCheckpoints ## This is a single player mod.
    - name: AdditionalBuildcraftObjects
    - name: AdditionalBuildcraftPipes
    - name: AdvancedMachines
    - name: AdvancedPowerManagement
    - name: AdvancedReactors
    - name: AdvancedReactors
    - name: AnimationAPI
    - name: AppliedEnergistics
    - name: Aquaculture
    - name: ArchimedesShips
    - name: ArmorStatusHUD
    - name: ArsMagica2
    - name: AtomicScience
    - name: BILLUND
    - name: BackTools
    - name: BalkonsWeaponMod
    - name: BechillTPS
    - name: BetterDungeons
    - name: BetterGrassAndLeaves
    - name: BiblioCraft
    - name: BiblioWoods[BiomesOPlenty]
    - name: BiblioWoods[ExtraBiomesXL]
    - name: BiblioWoods[Forestry]
    - name: BiblioWoods[Highlands]
    - name: BiblioWoods[Natura]
    - name: BigReactors
    - name: BinniesMods
    - name: BiomesOPlenty
    - name: BuffBarMod
    - name: Buildcraft
    - name: Carpenter'sBlocks
    - name: ChargePads
    - name: ChatBubbles
    - name: ChestTransporter
    - name: ChickenChunks
    - name: Chisel ## *check*
    - name: CodeChickenCore
    - name: ComputerCraft
    - name: CraftGuide
    - name: DamageIndicators
    - name: DartCraft
    - name: DeathCounter
    - name: DenPipes
    - name: DimensionalDoors
    - name: Discocraft
    - name: DoubleDoors
    - name: DragonAPI
    - name: Durability101
    - name: DynamicLiquidTanks
    - name: EiraIRC
    - name: EnchantingPlus
    - name: EnderIO
    - name: EnderStorage
    # - name: EnergyManipulation ## removed due to OP and laggy.
    - name: EngineersToolbox
    - name: ExpandedRedstone
    - name: ExtendedFuels
    - name: ExtendedRedstone
    - name: ExtraBiomesXL
    - name: ExtraCells
    - name: ExtraUtilities
    - name: Extratic
    - name: Factorization
    - name: Forestry
    - name: ForgeMultipart
    - name: FrogCraft
    - name: Galacticraft
    - name: Gany'sNetherMod ## *check*
    - name: GateCopy
    - name: GravitationSuite
    - name: GregTech
    - name: GrowthCraft
    - name: Highlands
    - name: IC2BackpackHUD
    - name: IC2BackpackHUD
    - name: Immibis'sMicroblocks
    - name: ImmibisCore
    - name: ImmibisPeripherals
    - name: IndustrialCraft2
    - name: InfernalMobs
    - name: InfiniTubes
    - name: InventoryTweaks
    - name: IronChests
    - name: KeithyUtils
    - name: LiquidXP
    - name: LogisticsPipes
    - name: MFR-ForestryTrees
    - name: MagicBees
    - name: MagicYarn
    - name: MapWriter
    - name: Matmos
    - name: Mekanism
    - name: Metallurgy
    - name: MinecraftForge
    - name: MinefactoryReloaded
    - name: MiscPeripherals
    - name: MobAmputation
    - name: MobDismemberment
    - name: ModularForcefieldSystem
    - name: ModularPowersuits
    - name: ModularPowersuits-Addons
    - name: MoreRecords-Core
    - name: MoreRecords-KingLunar
    - name: MoreRecords-MLP
    - name: Morph
    - name: MouseTweaks
    - name: MutantCreatures
    - name: Mystcraft
    - name: NEIAddons
    - name: NEIPlugins
    - name: Natura
    - name: Netherstuffs
    - name: NoSoundLag
    - name: NotEnoughItems
    - name: NotEnoughItems
    - name: NuclearControl
    - name: ObsidiPlates
    - name: Omnitools
    - name: OpenBlocks
    - name: OpenCCSensors
    - name: OpenPeripheral
    - name: Optifine
    - name: PluginsForForestry
    - name: PortalGun
    - name: PowerCrystalsCore
    - name: PresenceFootsteps
    - name: ProjectRed
    - name: Railcraft
    - name: RandomThings
    - name: ReactorCraft
    - name: RedIO
    - name: RedLogic
    - name: RedLogic
    - name: RedstoneInMotion
    - name: ResonantInduction
    - name: RopesPlus
    - name: RotaryCraft
    - name: ScalaLibrary
    - name: Schematica
    - name: SecretRoomsMod
    - name: SolitaryCraftOreMod
    - name: Somnia ## *check*
    - name: StargateTech2
    - name: Steve'sCarts2
    - name: SuperCraftingFrame
    - name: Switches
    - name: TabbyChat
    - name: Thaumcraft
    - name: ThaumcraftExtras ## Lots of problems.
    - name: ThaumicTinkerer
    - name: ThermalExpansion
    - name: TickProfiler
    - name: TinkersConstruct
    - name: TinkersConstructRecovery
    - name: ToolBelts
    - name: Translocator
    - name: Treecapitator
    - name: TrussMod
    - name: TubeStuff
    - name: TukMC
    - name: TwilightForest
    - name: UndergroundBiomes
    - name: UniversalElectricity
    - name: VoxelMap
    - name: WR-CBE
    - name: Waila
    - name: Xhamolk'sAdvancedCraftingTable
    - name: bspkrsCore
    - name: denLib
    - name: iChunUtil
    - name: qCraft
